### ISSUE TITLE
Datasource does not support alerting queries

### ISSUE THREAD

**Issue by frankidem** [NovatecConsulting/ca-apm-grafana-datasource#5]
It will be very very useful if we can use alerting mechanism of grafana.
Do you plan to add this to your implementation?

**Comment by oberschlauberger** [comment]
Hi, we will not implement alerting for this data source plugin.

When we started development of this Grafana integration for APM, we decided against this because a) Grafana alerting was rather immature at the time and b) it was predictable that Grafana's continuous polling for alerting would not work well with APM's slow SOAP interface that we use for querying metrics.

I suggest using APM's own alerting mechanisms instead. We achieved good results using APM's alerting and visualizing alert status in Grafana.

**Comment by frankidem** [comment]
Thank you
